//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empresa_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstacionServicio
    {
        public int Id { get; set; }
        public string Direccion { get; set; }
        public int CapacidadMaxima { get; set; }
        public string Region { get; set; }
        public string HorarioDeAtencion { get; set; }
    }
}
